packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  'esbuild': true
  'proto-tailwindcss-clrs': true

minimumReleaseAgeExclude:
  - '@stencil/core@4.45.0'
  - autoprefixer@10.6.0
  - proto-tailwindcss-clrs@0.0.547
