packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  'esbuild': true
  'proto-tailwindcss-clrs': true

minimumReleaseAgeExclude:
  - '@stencil/core@4.45.2'
  - postcss@8.5.29
  - proto-tailwindcss-clrs@0.0.558
