/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ProtoTinker {
        "tag": string;
    }
}
declare global {
    interface HTMLProtoTinkerElement extends Components.ProtoTinker, HTMLStencilElement {
    }
    var HTMLProtoTinkerElement: {
        prototype: HTMLProtoTinkerElement;
        new (): HTMLProtoTinkerElement;
    };
    interface HTMLElementTagNameMap {
        "proto-tinker": HTMLProtoTinkerElement;
    }
}
declare namespace LocalJSX {
    interface ProtoTinker {
        "tag"?: string;
    }
    interface IntrinsicElements {
        "proto-tinker": ProtoTinker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "proto-tinker": LocalJSX.ProtoTinker & JSXBase.HTMLAttributes<HTMLProtoTinkerElement>;
        }
    }
}
