/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ProtoTinker {
        /**
          * @default 'proto-tinker'
         */
        "tag": string;
    }
}
declare global {
    interface HTMLProtoTinkerElement extends Components.ProtoTinker, HTMLStencilElement {
    }
    var HTMLProtoTinkerElement: {
        prototype: HTMLProtoTinkerElement;
        new (): HTMLProtoTinkerElement;
    };
    interface HTMLElementTagNameMap {
        "proto-tinker": HTMLProtoTinkerElement;
    }
}
declare namespace LocalJSX {
    interface ProtoTinker {
        /**
          * @default 'proto-tinker'
         */
        "tag"?: string;
    }

    interface ProtoTinkerAttributes {
        "tag": string;
    }

    interface IntrinsicElements {
        "proto-tinker": Omit<ProtoTinker, keyof ProtoTinkerAttributes> & { [K in keyof ProtoTinker & keyof ProtoTinkerAttributes]?: ProtoTinker[K] } & { [K in keyof ProtoTinker & keyof ProtoTinkerAttributes as `attr:${K}`]?: ProtoTinkerAttributes[K] } & { [K in keyof ProtoTinker & keyof ProtoTinkerAttributes as `prop:${K}`]?: ProtoTinker[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "proto-tinker": LocalJSX.IntrinsicElements["proto-tinker"] & JSXBase.HTMLAttributes<HTMLProtoTinkerElement>;
        }
    }
}
